<a href="https://colab.research.google.com/github/Hkd225/Mental-Health-Risk-Classification-Project/blob/main/Mental_Health_Disorder_Risk_Assessment_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import os
import kagglehub
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
import joblib

path = kagglehub.dataset_download("algozee/mental-health-disorder-risk-assessment-dataset")

Using Colab cache for faster access to the 'mental-health-disorder-risk-assessment-dataset' dataset.

In [2]:
df = pd.read_csv(os.path.join(path, 'mental_health_risk_dataset.csv'))

In [3]:
df.head()

,age,gender,marital_status,education_level,employment_status,sleep_hours,physical_activity_hours_per_week,screen_time_hours_per_day,social_support_score,work_stress_level,...,depression_score,stress_level,mood_swings_frequency,concentration_difficulty_level,panic_attack_history,family_history_mental_illness,previous_mental_health_diagnosis,therapy_history,substance_use,mental_health_risk
0,56,Other,Single,Bachelor,Unemployed,8.6,2.8,9.6,7,10,...,4,8,8,3,1,0,1,1,1,1
1,47,Male,Single,Bachelor,Unemployed,4.5,2.7,3.0,10,6,...,7,4,9,3,0,0,0,0,0,0
2,56,Female,Divorced,Bachelor,Student,3.1,14.1,7.2,10,5,...,3,1,4,2,1,1,1,1,1,2
3,59,Other,Married,Bachelor,Employed,7.0,0.5,10.3,2,10,...,8,5,2,5,1,1,0,1,1,2
4,58,Male,Single,High School,Self-Employed,5.1,2.5,1.2,8,1,...,8,3,3,1,0,0,1,0,1,0

In [4]:
df.describe()

,age,sleep_hours,physical_activity_hours_per_week,screen_time_hours_per_day,social_support_score,work_stress_level,academic_pressure_level,job_satisfaction_score,financial_stress_level,working_hours_per_week,...,depression_score,stress_level,mood_swings_frequency,concentration_difficulty_level,panic_attack_history,family_history_mental_illness,previous_mental_health_diagnosis,therapy_history,substance_use,mental_health_risk
count,25000.000000,25000.000000,25000.000000,25000.000000,25000.00000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,...,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000
mean,39.072560,6.509516,7.515400,6.469132,5.50840,5.517080,5.445880,5.471040,5.495080,45.049600,...,5.534000,5.520480,5.512880,5.488240,0.497840,0.504280,0.504160,0.501640,0.499120,0.778520
std,12.404948,2.015586,4.324346,3.167682,2.88694,2.864548,2.864479,2.867816,2.881636,14.683297,...,2.870048,2.873213,2.870596,2.873178,0.500005,0.499992,0.499993,0.500007,0.500009,0.691409
min,18.000000,3.000000,0.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,20.000000,...,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,28.000000,4.800000,3.800000,3.700000,3.00000,3.000000,3.000000,3.000000,3.000000,32.000000,...,3.000000,3.000000,3.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,39.000000,6.500000,7.500000,6.500000,5.00000,6.000000,5.000000,5.000000,5.000000,45.000000,...,6.000000,6.000000,6.000000,5.000000,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000
75%,50.000000,8.200000,11.300000,9.200000,8.00000,8.000000,8.000000,8.000000,8.000000,58.000000,...,8.000000,8.000000,8.000000,8.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
max,60.000000,10.000000,15.000000,12.000000,10.00000,10.000000,10.000000,10.000000,10.000000,70.000000,...,10.000000,10.000000,10.000000,10.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 25 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   age                               25000 non-null  int64
 1   gender                            25000 non-null  object
 2   marital_status                    25000 non-null  object
 3   education_level                   25000 non-null  object
 4   employment_status                 25000 non-null  object
 5   sleep_hours                       25000 non-null  float64
 6   physical_activity_hours_per_week  25000 non-null  float64
 7   screen_time_hours_per_day         25000 non-null  float64
 8   social_support_score              25000 non-null  int64
 9   work_stress_level                 25000 non-null  int64
 10  academic_pressure_level           25000 non-null  int64
 11  job_satisfaction_score            25000 non-null  int64
 12  financial_stress_level            25000 non-null  int64
 13  working_hours_per_week            25000 non-null  int64
 14  anxiety_score                     25000 non-null  int64
 15  depression_score                  25000 non-null  int64
 16  stress_level                      25000 non-null  int64
 17  mood_swings_frequency             25000 non-null  int64
 18  concentration_difficulty_level    25000 non-null  int64
 19  panic_attack_history              25000 non-null  int64
 20  family_history_mental_illness     25000 non-null  int64
 21  previous_mental_health_diagnosis  25000 non-null  int64
 22  therapy_history                   25000 non-null  int64
 23  substance_use                     25000 non-null  int64
 24  mental_health_risk                25000 non-null  int64
dtypes: float64(3), int64(18), object(4)
memory usage: 4.8+ MB

In [6]:

X = df.drop('mental_health_risk', axis=1)
y = df['mental_health_risk']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

X_train = X_train.copy()
X_test = X_test.copy()

cols_to_encode = ['gender', 'marital_status', 'education_level', 'employment_status']

for col in cols_to_encode:
    le = LabelEncoder()
    X_train[col] = le.fit_transform(X_train[col])
    X_test[col] = le.transform(X_test[col])

In [18]:
X.head()

,age,gender,marital_status,education_level,employment_status,sleep_hours,physical_activity_hours_per_week,screen_time_hours_per_day,social_support_score,work_stress_level,...,anxiety_score,depression_score,stress_level,mood_swings_frequency,concentration_difficulty_level,panic_attack_history,family_history_mental_illness,previous_mental_health_diagnosis,therapy_history,substance_use
0,56,Other,Single,Bachelor,Unemployed,8.6,2.8,9.6,7,10,...,5,4,8,8,3,1,0,1,1,1
1,47,Male,Single,Bachelor,Unemployed,4.5,2.7,3.0,10,6,...,3,7,4,9,3,0,0,0,0,0
2,56,Female,Divorced,Bachelor,Student,3.1,14.1,7.2,10,5,...,8,3,1,4,2,1,1,1,1,1
3,59,Other,Married,Bachelor,Employed,7.0,0.5,10.3,2,10,...,9,8,5,2,5,1,1,0,1,1
4,58,Male,Single,High School,Self-Employed,5.1,2.5,1.2,8,1,...,1,8,3,3,1,0,0,1,0,1

In [7]:
scaler = MinMaxScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

X_train_scaled = pd.DataFrame(X_train_scaled, columns=X.columns)
X_test_scaled = pd.DataFrame(X_test_scaled, columns=X.columns)

In [19]:
X_train_scaled.head()

,age,gender,marital_status,education_level,employment_status,sleep_hours,physical_activity_hours_per_week,screen_time_hours_per_day,social_support_score,work_stress_level,...,anxiety_score,depression_score,stress_level,mood_swings_frequency,concentration_difficulty_level,panic_attack_history,family_history_mental_illness,previous_mental_health_diagnosis,therapy_history,substance_use
0,0.833333,0.5,0.5,0.333333,0.666667,0.071429,0.140000,0.700000,0.000000,0.222222,...,0.000000,0.111111,0.777778,0.777778,0.666667,1.0,0.0,1.0,1.0,0.0
1,1.000000,0.0,0.0,1.000000,0.666667,0.485714,0.980000,0.490909,0.444444,0.333333,...,0.444444,0.666667,0.000000,0.888889,0.666667,0.0,1.0,0.0,0.0,0.0
2,0.928571,1.0,0.0,0.333333,0.333333,0.842857,0.146667,0.781818,0.666667,0.222222,...,0.000000,0.777778,0.222222,0.777778,0.000000,0.0,1.0,1.0,0.0,1.0
3,0.809524,0.0,0.5,0.000000,0.666667,0.171429,0.593333,0.763636,0.222222,0.111111,...,0.000000,1.000000,0.888889,0.444444,0.444444,0.0,1.0,0.0,0.0,0.0
4,0.000000,0.0,0.0,0.000000,0.000000,0.742857,0.200000,0.018182,0.444444,0.222222,...,0.222222,0.333333,0.000000,0.444444,0.666667,0.0,0.0,1.0,0.0,1.0

In [8]:
model_rf = RandomForestClassifier(random_state=42)
model_rf.fit(X_train_scaled, y_train)

y_pred = model_rf.predict(X_test_scaled)

print(f"Akurasi Random Forest : {accuracy_score(y_test, y_pred) * 100:.2f}%\n")

Akurasi Random Forest : 97.02%

In [9]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

y_pred = model_rf.predict(X_test_scaled)

akurasi = accuracy_score(y_test, y_pred)
print(f"Akurasi Model: {akurasi * 100:.2f}%\n")
print("Laporan Klasifikasi:")
print(classification_report(y_test, y_pred))

Akurasi Model: 97.02%

Laporan Klasifikasi:
              precision    recall  f1-score   support

           0       0.99      1.00      1.00      1871
           1       0.95      0.99      0.97      2365
           2       1.00      0.83      0.91       764

    accuracy                           0.97      5000
   macro avg       0.98      0.94      0.96      5000
weighted avg       0.97      0.97      0.97      5000

In [10]:
from sklearn.linear_model import LogisticRegression

logreg_model = LogisticRegression(penalty='l2', multi_class='multinomial', solver='lbfgs', max_iter=1000, random_state=42)
logreg_model.fit(X_train_scaled, y_train)
y_pred_logreg = logreg_model.predict(X_test_scaled)

print("=== Hasil Logistic Regression (L2) ===")
print(f"Akurasi: {accuracy_score(y_test, y_pred_logreg) * 100:.2f}%")

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(

=== Hasil Logistic Regression (L2) ===
Akurasi: 75.00%

In [11]:
from sklearn.svm import SVC

svm_model = SVC(kernel='rbf', random_state=42)
svm_model.fit(X_train_scaled, y_train)
y_pred_svm = svm_model.predict(X_test_scaled)

print("=== Hasil Support Vector Machine (SVM) ===")
print(f"Akurasi: {accuracy_score(y_test, y_pred_svm) * 100:.2f}%")

=== Hasil Support Vector Machine (SVM) ===
Akurasi: 81.60%

In [12]:
from xgboost import XGBClassifier

xgb_model = XGBClassifier(random_state=42, eval_metric='mlogloss')
xgb_model.fit(X_train_scaled, y_train)
y_pred_xgb = xgb_model.predict(X_test_scaled)

print("=== Hasil XGBoost ===")
print(f"Akurasi: {accuracy_score(y_test, y_pred_xgb) * 100:.2f}%")

=== Hasil XGBoost ===
Akurasi: 99.88%

In [13]:
print("\n--- LAPORAN KLASIFIKASI LENGKAP ---")

print("\n1. LOGISTIC REGRESSION (L2)")
print(classification_report(y_test, y_pred_logreg))

print("\n2. SUPPORT VECTOR MACHINE (SVM)")
print(classification_report(y_test, y_pred_svm))

print("\n3. XGBOOST")
print(classification_report(y_test, y_pred_xgb))

print("\n4. RANDOM FOREST")
print(classification_report(y_test, y_pred))

--- LAPORAN KLASIFIKASI LENGKAP ---

1. LOGISTIC REGRESSION (L2)
              precision    recall  f1-score   support

           0       0.79      0.76      0.78      1871
           1       0.72      0.78      0.75      2365
           2       0.77      0.63      0.69       764

    accuracy                           0.75      5000
   macro avg       0.76      0.72      0.74      5000
weighted avg       0.75      0.75      0.75      5000


2. SUPPORT VECTOR MACHINE (SVM)
              precision    recall  f1-score   support

           0       0.87      0.83      0.85      1871
           1       0.78      0.86      0.81      2365
           2       0.83      0.66      0.74       764

    accuracy                           0.82      5000
   macro avg       0.83      0.78      0.80      5000
weighted avg       0.82      0.82      0.82      5000


3. XGBOOST
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1871
           1       1.00      1.00      1.00      2365
           2       1.00      0.99      1.00       764

    accuracy                           1.00      5000
   macro avg       1.00      1.00      1.00      5000
weighted avg       1.00      1.00      1.00      5000


4. RANDOM FOREST
              precision    recall  f1-score   support

           0       0.99      1.00      1.00      1871
           1       0.95      0.99      0.97      2365
           2       1.00      0.83      0.91       764

    accuracy                           0.97      5000
   macro avg       0.98      0.94      0.96      5000
weighted avg       0.97      0.97      0.97      5000

In [15]:
encoders = {}
for col in cols_to_encode:
    le = LabelEncoder()
    X_train[col] = le.fit_transform(X_train[col])
    X_test[col] = le.transform(X_test[col])
    encoders[col] = le

joblib.dump(model_rf, 'model_rf.pkl')
joblib.dump(logreg_model, 'model_logreg.pkl')
joblib.dump(svm_model, 'model_svm.pkl')
joblib.dump(xgb_model, 'model_xgb.pkl')

joblib.dump(scaler, 'scaler.pkl')
joblib.dump(encoders, 'encoders.pkl')

print("Semua model, scaler, dan encoder berhasil disimpan!")

Semua model, scaler, dan encoder berhasil disimpan!

# Restart runtime tekan library mulai dari loaded di bawah jika ingin test pakai data baru, untuk coba2 model bisa ganti model logreg, rf, svm, xgb

In [32]:
loaded_model = joblib.load('model_logreg.pkl')
loaded_scaler = joblib.load('scaler.pkl')
loaded_encoders = joblib.load('encoders.pkl')

In [33]:
input_data = {
    'age': [30],
    'gender': ['Male'],
    'marital_status': ['Married'],
    'education_level': ['Master'],
    'employment_status': ['Employed'],
    'sleep_hours': [7.0],
    'physical_activity_hours_per_week': [5.0],
    'screen_time_hours_per_day': [6.0],
    'social_support_score': [8],
    'work_stress_level': [4],
    'academic_pressure_level': [1],
    'job_satisfaction_score': [7],
    'financial_stress_level': [3],
    'working_hours_per_week': [40],
    'anxiety_score': [2],
    'depression_score': [2],
    'stress_level': [3],
    'mood_swings_frequency': [1],
    'concentration_difficulty_level': [2],
    'panic_attack_history': [0],
    'family_history_mental_illness': [0],
    'previous_mental_health_diagnosis': [0],
    'therapy_history': [0],
    'substance_use': [0]
}

df_input = pd.DataFrame(input_data)

cols_to_encode = ['gender', 'marital_status', 'education_level', 'employment_status']

for col in cols_to_encode:
    df_input[col] = loaded_encoders[col].transform(df_input[col])

input_scaled = loaded_scaler.transform(df_input)
input_scaled_df = pd.DataFrame(input_scaled, columns=df_input.columns)

hasil_prediksi = loaded_model.predict(input_scaled_df)

hasil_prediksi = loaded_model.predict(input_scaled_df)[0]

mapping_risiko = {
    0: "Low Risk (Risiko Rendah)",
    1: "Moderate Risk (Risiko Sedang)",
    2: "High Risk (Risiko Tinggi)"
}

print(f"Hasil Prediksi Mental Health Risk: {hasil_prediksi} -> {mapping_risiko[hasil_prediksi]}")

Hasil Prediksi Mental Health Risk: 0 -> Low Risk (Risiko Rendah)

In [34]:
input_data_5 = {
    'age': [28, 21, 35, 42, 25],
    'gender': ['Female', 'Male', 'Male', 'Female', 'Male'],
    'marital_status': ['Married', 'Single', 'Divorced', 'Single', 'Single'],
    'education_level': ['Master', 'High School', 'Bachelor', 'Bachelor', 'High School'],
    'employment_status': ['Employed', 'Student', 'Employed', 'Unemployed', 'Unemployed'],
    'sleep_hours': [8.0, 6.0, 5.0, 4.5, 3.0],
    'physical_activity_hours_per_week': [6.0, 3.0, 1.0, 0.0, 0.0],
    'screen_time_hours_per_day': [4.0, 8.0, 10.0, 12.0, 14.0],
    'social_support_score': [9, 6, 4, 3, 1],
    'work_stress_level': [2, 0, 8, 0, 0],
    'academic_pressure_level': [0, 7, 0, 0, 0],
    'job_satisfaction_score': [8, 5, 3, 0, 0],
    'financial_stress_level': [2, 5, 7, 9, 10],
    'working_hours_per_week': [35, 20, 55, 0, 0],
    'anxiety_score': [1, 4, 6, 8, 10],
    'depression_score': [1, 3, 6, 7, 10],
    'stress_level': [2, 5, 8, 8, 10],
    'mood_swings_frequency': [0, 2, 3, 4, 5],
    'concentration_difficulty_level': [1, 3, 6, 8, 10],
    'panic_attack_history': [0, 0, 0, 1, 1],
    'family_history_mental_illness': [0, 0, 1, 0, 1],
    'previous_mental_health_diagnosis': [0, 0, 0, 1, 1],
    'therapy_history': [0, 0, 1, 0, 1],
    'substance_use': [0, 0, 0, 1, 1]
}

df_input_5 = pd.DataFrame(input_data_5)

for col in cols_to_encode:
    df_input_5[col] = loaded_encoders[col].transform(df_input_5[col])

input_scaled_5 = loaded_scaler.transform(df_input_5)
input_scaled_df_5 = pd.DataFrame(input_scaled_5, columns=df_input_5.columns)

hasil_prediksi_5 = loaded_model.predict(input_scaled_df_5)

mapping_risiko = {
    0: "Low Risk (Risiko Rendah)",
    1: "Moderate Risk (Risiko Sedang)",
    2: "High Risk (Risiko Tinggi)"
}

print("=== HASIL PREDIKSI 5 SKENARIO BARU ===\n")
for i, hasil in enumerate(hasil_prediksi_5):
    print(f"Profil {i+1} -> Hasil Prediksi: {hasil} ({mapping_risiko[hasil]})")

=== HASIL PREDIKSI 5 SKENARIO BARU ===

Profil 1 -> Hasil Prediksi: 0 (Low Risk (Risiko Rendah))
Profil 2 -> Hasil Prediksi: 0 (Low Risk (Risiko Rendah))
Profil 3 -> Hasil Prediksi: 1 (Moderate Risk (Risiko Sedang))
Profil 4 -> Hasil Prediksi: 2 (High Risk (Risiko Tinggi))
Profil 5 -> Hasil Prediksi: 2 (High Risk (Risiko Tinggi))

In [35]:
probabilitas_5 = loaded_model.predict_proba(input_scaled_df_5)

print("=== PROBABILITAS (KEYAKINAN MODEL) ===\n")
for i, prob in enumerate(probabilitas_5):
    print(f"Profil {i+1}:")
    print(f" - Low Risk (0)     : {prob[0]*100:.1f}%")
    print(f" - Moderate Risk (1): {prob[1]*100:.1f}%")
    print(f" - High Risk (2)    : {prob[2]*100:.1f}%\n")

=== PROBABILITAS (KEYAKINAN MODEL) ===

Profil 1:
 - Low Risk (0)     : 99.9%
 - Moderate Risk (1): 0.1%
 - High Risk (2)    : 0.0%

Profil 2:
 - Low Risk (0)     : 96.6%
 - Moderate Risk (1): 3.4%
 - High Risk (2)    : 0.0%

Profil 3:
 - Low Risk (0)     : 4.5%
 - Moderate Risk (1): 73.9%
 - High Risk (2)    : 21.6%

Profil 4:
 - Low Risk (0)     : 0.2%
 - Moderate Risk (1): 26.8%
 - High Risk (2)    : 73.0%

Profil 5:
 - Low Risk (0)     : 0.0%
 - Moderate Risk (1): 0.1%
 - High Risk (2)    : 99.9%